WIP: Legislative Process Page Sidebar
wevisdemo/parliament-watch pull request #37
Opened 2023-10-19 01:16 UTC by thasarito

Accidentally clode the previous one

related issue: #28

2023-10-19 03:20 UTC, thasarito commented
Fixed what was mentioned in #33 @Th1nkK1D 

Long time no see indeed, missed this community kub

2023-10-19 05:29 UTC, Th1nkK1D requested changes
Found a strange bug on a small screenshot.
- An overlayed element appears which dims the content below it.
- When I click on it, it disappears and the sidebar moves to a strange location.

[Screencast from 2023-10-19 12-14-04.webm](https://github.com/wevisdemo/parliament-watch/assets/8860448/964e4dc1-ebfe-4461-be7d-509128cff3e7)

I just merged one PR that fixed some issues with the Navbar, maybe you can try to pull from the `main` branch to see if the issue is still there.

One more point, Regarding the small screen size, I understand that the designer wants the sidebar to have the same width as the content below.
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/c6056d1d-988b-43f4-aeb3-5628602100ce)

Now we have a lot of horizontal margins and some overflow at the bottom.

![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/5cd9c852-0829-4bad-967c-89559471493f)

PS. I tested on the latest Firefox and Chromium on Linux. Not sure if you can reproduce this on your computer.

2023-10-19 05:29 UTC, Th1nkK1D commented on src/components/LegislativeProcess/Sidebar.svelte
> +					<SideNavMenuItem href={`#${item.text}`}>{item.text}</SideNavMenuItem>
In Svelte, You can add variable brackets in a string like
```svelte
<SideNavMenuItem href="#{item.text}">{item.text}</SideNavMenuItem>
```

2023-10-19 10:46 UTC, Icyscools requested changes
I just want to know how to implement this sidebar and found this typo error. 😅

2023-10-19 10:46 UTC, Icyscools commented on src/components/LegislativeProcess/Sidebar.svelte
> +				{ text: 'หน้าที่ขออง ส.ส.' },
```suggestion
				{ text: 'หน้าที่ของ ส.ส.' },
```

2023-10-20 14:23 UTC, thasarito commented
fixed @Th1nkK1D

2023-10-21 02:12 UTC, Th1nkK1D approved these changes
LGTM! Thank you for your contribution. We will contact you at the end of this month about the sticker!

2023-10-21 02:12 UTC, merged

2023-11-03 04:41 UTC, Th1nkK1D commented
Thank you for the Hacktoberfest participation! Please fill up the [form](https://airtable.com/appgGYIo458vDkrQN/shrZMe2hZBa6tQXvz) before 6 November 2023 to receive our limited-edition stickers.