badgooooor/#40 Legistration process page -- overview section
wevisdemo/parliament-watch pull request #51
Opened 2023-10-22 08:51 UTC by badgooooor

### Description
- Add content in legistration process page -- overview section
- Note: I have a bit problem on exporting and optimize process images (the 3 steps one) that there is still some white background leaked to image. I've tried on both squoosh.app or ImageOptim and they didn't remove it 😢.

**Desktop**
![image](https://github.com/wevisdemo/parliament-watch/assets/14361087/9a416bdf-5b90-4ae3-b729-3694136776bc)
![image](https://github.com/wevisdemo/parliament-watch/assets/14361087/2065eff5-3967-4ac0-a354-73a1ec4cf4b0)

**Mobile**
![image](https://github.com/wevisdemo/parliament-watch/assets/14361087/2ac1b16c-a12d-4976-a31e-50dd0179fffa)
![image](https://github.com/wevisdemo/parliament-watch/assets/14361087/72df148d-488f-4377-b486-15b2f8a2a169)

2023-10-24 07:39 UTC, Th1nkK1D requested changes
Thanks for the PR! I left some comments. I also found an image issue. I will talk with the designer and get back to you since it is not correct when exporting from Figma. Image optimizer just compresses the image to have a smaller size so it won't help.

2023-10-24 07:39 UTC, Th1nkK1D commented on src/components/LegislativeProcess/ProcessCard.svelte
> +	<img src={imgSrc} alt={`process-step-${title}`} />
In Svelte, you can do
```svelte
<img src={imgSrc} alt="process-step-{title}" />
```
which is more concise.

2023-10-24 07:39 UTC, Th1nkK1D commented on src/routes/legislative-process/+page.svelte
> +					<img
Need a margin between paragraph and image. Please refer to Figma.

![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/a447a68a-3edb-4c01-9b1c-7276ba59b382)

2023-10-24 07:39 UTC, Th1nkK1D commented on src/routes/legislative-process/+page.svelte
> +					<p class="body-02 mt-6">
Some sentences in this paragraph, and also other paragraphs below, are bold. Please recheck with Figma.

2023-10-24 08:07 UTC, badgooooor commented
> Thanks for the PR! I left some comments. I also found an image issue. I will talk with the designer and get back to you since it is not correct when exporting from Figma. Image optimizer just compresses the image to have a smaller size so it won't help.

Please ping me if images are updated. I'll retry exporting it.

2023-10-24 08:58 UTC, Th1nkK1D commented on src/components/LegislativeProcess/ProcessCard.svelte
> +	<img src={imgSrc} alt="process-step-${title}" />
Svelte doesn't use `$` in front of the variable bracket when used in an attribute. In this case, if the title = "ชื่อ", the alt will be "process-step-$ชื่อ" which I'm not sure if it is what you want.

Other things looking good now. I already reach out to the designer and they should fix the image problem. I'll let you know when it's ready so you can export the correct images.

2023-10-25 15:03 UTC, Th1nkK1D commented
> Please ping me if images are updated. I'll retry exporting it.

Our designers fix it. Please try to export the images again.

2023-10-28 14:43 UTC, badgooooor commented
Updated images.

<img width="626" alt="image" src="https://github.com/wevisdemo/parliament-watch/assets/14361087/42ab0836-e3ee-4013-b9ab-4d6dbf569c05">

<img width="611" alt="image" src="https://github.com/wevisdemo/parliament-watch/assets/14361087/6fb3dad0-77f6-43a9-9e1a-1e1930545f27">

2023-10-30 04:30 UTC, Th1nkK1D approved these changes

2023-10-30 04:31 UTC, Th1nkK1D commented
LGTM! Thank you for another PR ;)

2023-10-30 04:31 UTC, merged