#42 legislative process content 3/9
wevisdemo/parliament-watch pull request #59
Opened 2023-10-30 17:42 UTC by l3luescreen

**Additional:** Reorder carbon's style to be able to use typography in carbon component

<img width="759" alt="image" src="https://github.com/wevisdemo/parliament-watch/assets/42911520/8e1399bf-069e-46df-87ce-d7b1aadf027c">

Mobile view
![image](https://github.com/wevisdemo/parliament-watch/assets/42911520/3f7ae009-836f-4215-8e2d-c710844a5b3a)

2023-10-31 03:46 UTC, Th1nkK1D requested changes
Thank you for the PR! Everything is working as expected. I have only some feedback about the code.

2023-10-31 03:46 UTC, Th1nkK1D commented on src/components/BillStatusCard/BillStatusCard.story.svelte
Let's remove this story file because we are not going to use this component somewhere else.

2023-10-31 03:46 UTC, Th1nkK1D commented on src/components/BillStatusCard/BillStatusCard.svelte
Because we used this component only on the legislative-process page, let's move it to `src/components/LegislativeProcess/BillStatusCard.svelte`

2023-10-31 03:46 UTC, Th1nkK1D commented on src/components/BillStatusCard/BillStatusCard.svelte
> +	// export let billType: string;
Remove unused comment

2023-10-31 03:46 UTC, Th1nkK1D commented on src/routes/legislative-process/+page.svelte
> +	import { BillStatus } from '$models/bill';
Move `import` up above `day.js` to keep it together.

2023-10-31 03:46 UTC, Th1nkK1D commented on src/routes/legislative-process/+page.svelte
> +								class={billStatus.class}
You can also spread an object as props
```svelte
<BillStatusCard {...billStatus} />
```

2023-10-31 03:46 UTC, Th1nkK1D commented on src/routes/legislative-process/+page.svelte
> +	let billStatuses = [
This variable is never changed. Use `const` instead.

2023-10-31 03:46 UTC, Th1nkK1D commented on src/routes/legislative-process/+page.svelte
> +	let billUrl = '#';
Couldn't find any usage of these variables. Did you forget to remove it?

2023-10-31 16:00 UTC, l3luescreen commented
All requested changes have been fixed. Feel free to review it again. Sorry for the small mistake kub.

2023-11-01 06:46 UTC, Th1nkK1D approved these changes
LGTM! Don't worry it's not a mistake. Thank you for your contribution. We will contact you about the stickers soon.

2023-11-01 06:48 UTC, merged

2023-11-03 04:43 UTC, Th1nkK1D commented
Thank you for the Hacktoberfest participation! Please fill up the [form](https://airtable.com/appgGYIo458vDkrQN/shrZMe2hZBa6tQXvz) before 6 November 2023 to receive our limited-edition stickers.