[WIP] Add bills page
wevisdemo/parliament-watch pull request #65
Opened 2023-11-23 14:42 UTC by JaeAiKay

2023-12-13 07:28 UTC, Th1nkK1D requested changes

2023-12-13 07:28 UTC, Th1nkK1D commented on src/components/bills/CoProposer.svelte
> +				<img src={logo ? logo : ''} alt="" />
If logo is `undefined`, we better not render the `img` with `{#if}`

2023-12-13 07:28 UTC, Th1nkK1D commented on src/components/bills/Progress.svelte
> +	import type { VotingResultSummary } from '../../routes/bills/[id]/+page';
I think we need to refactor this. Component should be independent from the route so we should not import anything from the route.

1. Please check if the `VoteCardProps` is the same with`VoteCard` component props. Then we can use 
```ts
import type { ComponentProps } from 'svelte';

ComponentProps<VoteCard>
```
2. We can declare the type definition and export it in `<script lang="ts" context="module">` see `DataPage` component for an example. Then the route should import from here.

2023-12-13 07:28 UTC, Th1nkK1D commented on src/routes/bills/[id]/+page.svelte
> +				{#if mergedBills !== undefined && mergedBills.length > 0}
We can make it more concise with optional chaining
```ts
{#if mergedBills?.length > 0}
```

2023-12-13 07:28 UTC, Th1nkK1D commented on src/routes/bills/[id]/+page.svelte
> +								{#if bill.coProposedByPoliticians.length > 8}
We should avoid magic number, people won't understand what is it, and if they want to change, how many places they need to change. So better declared it in `const` first like
```ts
const MAX_DISPLAY_COPROPOSER = 8;
```

2023-12-13 07:28 UTC, Th1nkK1D commented on src/routes/bills/[id]/+page.svelte
> +										{#if i < 8}
We should put if outside the each to avoid looping and render nothing.

2023-12-13 07:28 UTC, Th1nkK1D commented on src/routes/bills/[id]/+page.svelte
> +					<BillStatusTag isLarge={true} status={bill.status} />
We can omit `true` value from prop

```ts
<BillStatusTag isLarge status={bill.status} />
```

2023-12-13 07:28 UTC, Th1nkK1D commented on src/routes/bills/[id]/+page.svelte
> +							event={events[i]}
I think you don't need range

```svelte
{#each events as event}
		<Progress
			event={event}
```

2023-12-13 07:28 UTC, Th1nkK1D commented on src/routes/bills/[id]/+page.svelte
> +</div> -->
This can be removed

2023-12-20 06:41 UTC, Th1nkK1D commented
@JaeAiKay ไม่แน่ใจว่าอันนี้คือเสร็จยังนะ

2023-12-20 10:58 UTC, JaeAiKay commented
@Th1nkK1D เสร็จเรียบร้อยค่าา

2023-12-20 11:13 UTC, Th1nkK1D approved these changes

2023-12-20 11:15 UTC, Th1nkK1D commented
@JaeAiKay มี merge conflict อยากฝากลองดูว่าแก้ได้ไหม

2023-12-21 06:21 UTC, merged