WIP VoteCard Component #5
wevisdemo/parliament-watch pull request #8
Opened 2023-10-06 18:21 UTC by fResult

2023-10-09 07:21 UTC, Th1nkK1D requested changes
Overall, a very good PR. Thank you so much. Have a few comments and one strange issue on the story. The date is invalid when I choose a custom candidate name from the dropdown. Not sure if you can reproduce it.

![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/9d251e2e-1d66-4059-8194-ef3bb8b7de14)

2023-10-09 07:21 UTC, Th1nkK1D commented on src/components/votes/VoteCard.svelte
> +	<a class="vote-card--url after:inset no-underline after:absolute w-56" href={voting.sourceUrl}>
My bad for not clarifying this, the `sourceUrl` is the original document link for each voting from the parliament. The link from the card should refer to the voting page that can be referred to with the `id`. However, we don't have a page for voting yet, you can just use static `#` for now (the Svelte build will fail if we add a 404 path). And `sourceUrl`  needed to be removed from the type and mock data.

2023-10-09 07:21 UTC, Th1nkK1D commented on src/routes/assemblies/[id]/+page.svelte
> +	import VoteCard from '$components/votes/VoteCard.svelte';
Can you revert changes on this page because I want to throw all the data for another dev in the internal team 🙏

2023-10-09 10:18 UTC, fResult commented
> Overall, a very good PR. Thank you so much. Have a few comments and one strange issue on the story. The date is invalid when I choose a custom candidate name from the dropdown. Not sure if you can reproduce it.
> 
> ![image](https://user-images.githubusercontent.com/8860448/273516450-9d251e2e-1d66-4059-8194-ef3bb8b7de14.png)

I already fixed krub.\
But workaround fixing it a bit. 🥹
![image](https://github.com/wevisdemo/parliament-watch/assets/19329932/68c131b2-2135-415c-ba49-846d63c10878)

2023-10-09 14:55 UTC, Th1nkK1D approved these changes
LGTM! Thank you for your contribution. We will contact you back for the stickers at the end of this month.

2023-10-09 14:57 UTC, merged

2023-11-03 04:36 UTC, Th1nkK1D commented
Thank you for the Hacktoberfest participation! Please fill up the [form](https://airtable.com/appgGYIo458vDkrQN/shrZMe2hZBa6tQXvz) before 6 November 2023 to receive our limited-edition stickers.