Add UI for cabinet assembly changes page
wevisdemo/parliament-watch pull request #87
Opened 2024-08-06 08:16 UTC by JaeAiKay

resolve #84

2024-08-06 15:11 UTC, napatswift commented
หมายเหตุ:

ปฎิทินมีปัญหาเนื่องจากว่าไม่สามารถปรับได้ (เท่าที่ลองทำดู) ทำให้
- เลขปีในปฎิทินเป็นปี ค.ศ. แต่ตรง input text สามารถแสดงเป็น พ.ศ. ได้
- เพิ่มข้อมูลใต้วันที่ไม่ได้ตามการออกแบบ
<img width="306" alt="Screenshot 2567-08-06 at 22 08 02" src="https://github.com/user-attachments/assets/f5d9e721-60fd-4927-bd3f-e2c652238cfd">

2024-08-07 07:50 UTC, Th1nkK1D requested changes
ประทับใจจจจ อันที่เม้นๆไว้ฝากเช็คดูว่าแก้แล้ว behavior ยังถูกเหมือนเดิมไหม นอกจากนี้อยากให้ลองดูว่าแก้ timeline tooltip ได้ไหมเพราะ
1. hover เลือกวันที่ขอบๆ มันโดนตัดทิ้ง user ควรจะเห็นเพื่อรู้ว่ามันคือวันอะไร
![image](https://github.com/user-attachments/assets/758c2c9a-7f54-4eb8-b3be-a6e0af3e8082)
2. หาก hover วันที่อยู่ทางซ้ายของวันที่เลือก มันจะโดนวันที่เลือกบัง วันที่กำลัง hover ควรอยู่หน้าสุดเสมอ (ถ้า hover วันด้านขวาจะอยู่หน้าซึ่งถูกแล้ว)
![image](https://github.com/user-attachments/assets/8e3f4738-69d8-4da0-8fa9-978baaab8e12)

2024-08-07 07:50 UTC, Th1nkK1D commented on src/components/Assemblies/CabinetChanges/TimeLine.ts
> +			yaer: year,
`yaer` นี่สะกดผิดเปล่า มันถูกใช้ผิดหลายที่ด้วย

2024-08-07 07:50 UTC, Th1nkK1D commented on src/components/Assemblies/CabinetChanges/ChangeModal.svelte
> +	on:click:button--primary={() => handleSubmit()}
ใช้ arrow function ใหม่เรียก function ที่มีอยู่แล้วแบบไม่มี argument แบบ `on:click:button--primary={() => handleSubmit()}` ไม่น่าจำเป็น ควรเขียนแค่ `on:click:button--primary={handleSubmit}` ก็ใช้ได้และลดการเรียกฟังชั่้นซ้ำซ้อน

2024-08-07 07:50 UTC, Th1nkK1D commented on src/components/Assemblies/CabinetChanges/TimeItem.svelte
> +			style="{isHorizontal ? 'height' : 'width'}: {(day.out / max) * 100}%;"
`(day.out / max) * 100` อาจจะมีทศนิยมแบบไม่สิ้นสุด ซึ่งเคยเจอ CSS รับไม่ได้และกลายเป็น invalid style แนะนำให้ปัดเป็นจำนวนเต็มไปเลย เช่นใช้ `Math.round`

2024-08-07 07:50 UTC, Th1nkK1D commented on src/components/Assemblies/CabinetChanges/TimeLine.svelte
> +									style={compareDate(day.date, selectedDate) ? '' : 'background-color: white;'}
เห็นเรียก `compareDate(day.date, selectedDate)` ซ้ำหลายครั้ง Svelte มีท่า @const ที่เก็บตัวแปร ใส่ใต้ each/if ได้ https://svelte.dev/docs/special-tags#const

2024-08-07 07:50 UTC, Th1nkK1D commented on src/components/Assemblies/CabinetChanges/squareIcon.svelte
> +<svg {width} height={width} fill="none" xmlns="http://www.w3.org/2000/svg">
`xmlns="http://www.w3.org/2000/svg"` สามารถลบทิ้งได้ในกรณีที่ inline ใน code แต่ถ้าหากเป็น .svg ยังต้องเก็บไว้

2024-08-07 07:50 UTC, Th1nkK1D commented on src/components/Assemblies/RoleChanges/RoleChangeGroup.svelte
> +			: 'border-[1px] border-t-0 border-interactive-02/0'}
ยังไงก็มี `border-[1px] border-t-0` โยกออกมาข้างหน้านอกเงื่อนไขดีกว่าจะได้ไม่เขียนซ้ำ

2024-08-07 07:50 UTC, Th1nkK1D commented on src/components/Assemblies/RoleChanges/RoleChangeGroup.svelte
> +	}
เท่าที่ดูเร็วๆ isFocus ไม่ได้ถูกเปลี่ยนจาก code ส่วนอื่นอยู่แล้ว (และเราก็ควรเขียนในมุมที่ป้องกันรูปแบบนั้น) คิดว่าไม่ต้องเขียน let แยก เรารวมไปเลยได้ไหมเป็น

```svelte
$: isFocus =
      selectedDate &&
			selectedDate.getDate() === changeData[0].date.getDate() &&
			selectedDate.getMonth() === changeData[0].date.getMonth() &&
			selectedDate.getFullYear() === changeData[0].date.getFullYear();
```

หรือมีเคสที่เรานึกไม่ถึง

2024-08-07 07:50 UTC, Th1nkK1D commented on src/components/Assemblies/Tooltip.svelte
> +	<div role="tooltip" {id} class:bx--assistive-text={true} {style}>
ฝากลองดูว่าจริงๆ `class:bx--assistive-text={true}` มันมีค่าเท่ากับเขียน `class="bx--assistive-text"` แบบปกติเลยหรือเปล่า ถ้าใช่ ฝากแก้

2024-08-07 07:50 UTC, Th1nkK1D commented on src/components/DatePicker/DatePicker.svelte
> +	$: if (selectedDate) value = formatThaiDate(selectedDate);
เชียร์ให้รวมไม่เลยไม่ต้องมา let แยกเพราะไม่จำเป็นและประกาศให้คนรู้ด้วยว่า value ไม่ควรถูกแก้แต่ computed มาเท่านั้น

```
$: value = selectedDate ? formatThaiDate(selectedDate) : ''
```

2024-08-07 07:50 UTC, Th1nkK1D commented on src/components/DatePicker/DatePicker.svelte
> +		formatDate: (date) => formatThaiDate(date),
ควรเขียน `formatDate: formatThaiDate` ได้เลย

2024-08-07 07:50 UTC, Th1nkK1D commented on src/components/DatePicker/DatePicker.svelte
> +				'ธันวาคม'
`src/lib/date-parser.ts` ประกาศไว้แล้ว ควร import มาใช้

2024-08-07 07:50 UTC, Th1nkK1D commented on src/routes/assemblies/[id]/changes/+page.svelte
> +	$: isSticky = false;
`$:` ใช้เวลาที่มัน depend จาก props/reactive อื่นพอ แต่เวลาเรา assign ค่าคงที่ ค่าคงที่มันไม่มีทางเปลี่ยนอยู่แล้ว เช่น `$: innerWidth = 0;` มันไม่มีประโยชน์เพราะว่า 0 มันจะเป็ย 0 ตลอดไป ในเคสที่ประกาษตัวแปรเพื่อที่จะตัดสินใจเปลี่ยนเองด้วยการ assign ในภายหลังให้ใช้ `let`

ส่วน `$: isMD = innerWidth > 671;` make sense แล้วเพราะว่า innerWidth อาจจะถูกเปลี่ยนได้ และเมื่อไหร่ที่มันเปลี่ยน อยากให้คิด `isMD` ใหม่อัตโนมัติ

2024-08-07 07:50 UTC, Th1nkK1D commented on src/routes/assemblies/[id]/changes/+page.svelte
> +			on:click={() => (isMD ? {} : (openModal = true))}
ควรจะเขียน `() => if(!isMD) openModal = true` มากกว่า ฟังชั่นไม่ได้จำเป็นต้อง return empty object ที่ไม่ไได้ใช้ออกมา

2024-08-07 07:56 UTC, Th1nkK1D commented
เรา push ไป 1  commit เพื่อแก้ `squareIcon.svelte` เป็น `SquareIcon.svelte` คือบาง OS เป็น case-insensitive เช่น mac/windows ทำให้เรา import file ที่เขียน case ไม่ตรงได้ เช่นใน code เขียน import ตัวหน้าเป็นตัวใหญ่ แต่ไฟล์จริงเป็นตัวเล็ก (เป็นเหตุผลว่าทำไมทั้งสองคนไม่เจอปัญหา) แต่อย่าง linux (เครื่องเรา และที่สำคัญคือ ci/cd pipeline ที่จะทำการ build) มันเป็น case-sensitive หมายความว่าพิมพ์ใหญ่เล็กต้องตรงเป๊ะไม่งั้นมันจะหาไฟล์ไม่เจอ

2024-08-08 15:01 UTC, napatswift commented on src/components/DatePicker/DatePicker.svelte
> +		formatDate: (date) => formatThaiDate(date),
จริงด้วยย

2024-08-08 15:04 UTC, napatswift commented on src/components/DatePicker/DatePicker.svelte
> +		formatDate: (date) => formatThaiDate(date),
อ่อ ลืม `formatDate` มี 3 args ครับ
```
formatDate?: ((date: Date, format: string, locale: Locale) => string) | undefined
```

ส่วน `formatThaiDate` มี 2 args
```
formatThaiDate(date: Date, shortMonth?: boolean): string
```

เลยต้องไปท่านี้ครับ

2024-08-09 08:15 UTC, Th1nkK1D approved these changes

2024-08-09 08:16 UTC, merged